# Generated by Django 5.0.6 on 2025-06-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_ticket_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(default='auth0|685b0cb06f3a8c1dfaa36e8f', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
