# Generated by Django 5.0.6 on 2025-06-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
