# Generated by Django 5.0.6 on 2025-06-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_activationtoken_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ActivationToken',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
