# Generated by Django 5.0.6 on 2025-06-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='wagon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.wagon'),
        ),
        migrations.AlterField(
            model_name='wagon',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train'),
        ),
    ]
