# Generated by Django 5.0.6 on 2025-06-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_seat_wagon_alter_wagon_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wagon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
