# Generated by Django 5.0.6 on 2025-06-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_alter_seat_id_alter_train_id_alter_wagon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='wagon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='trains.wagon'),
        ),
        migrations.AlterField(
            model_name='wagon',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagons', to='trains.train'),
        ),
    ]
